Handle s3 upload errors to retry later

diff --git a/jobs/archiver/templates/bin/s3upload.cron.erb b/jobs/archiver/templates/bin/s3upload.cron.erb
--- a/jobs/archiver/templates/bin/s3upload.cron.erb
+++ b/jobs/archiver/templates/bin/s3upload.cron.erb
@@ -54,6 +54,7 @@ for FILE in $( ls *.log ) ; do
     echo "compressed ${FILE}"
 done
 
+EXIT_CODE=0
 
 for FILE in $( ls *.xz ) ; do
     echo "uploading ${FILE}"
@@ -64,7 +65,8 @@ for FILE in $( ls *.xz ) ; do
     S3GO_MIME="application/x-gzip"
     S3GO_SIGNATURE=$( echo -en "PUT\n${S3GO_MD5}\n${S3GO_MIME}\n${S3GO_NOW}\n${S3GO_ACL}\n/${S3_BUCKET}/${S3_PREFIX}${FILE}" | openssl sha1 -hmac "${S3_SECRET_ACCESS_KEY}" -binary | openssl enc -e -base64 )
 
-    curl \
+    R1=$( curl \
+        -s \
         -X PUT \
         -T "$FILE" \
         -H "$S3GO_ACL" \
@@ -72,15 +74,25 @@ for FILE in $( ls *.xz ) ; do
         -H "Date: $S3GO_NOW" \
         -H "Content-Type: application/x-gzip" \
         -H "Authorization: AWS ${S3_ACCESS_KEY_ID}:${S3GO_SIGNATURE}" \
-        "https://${S3_BUCKET}.${S3_ENDPOINT}/${S3_PREFIX}${FILE}"
+        "https://${S3_BUCKET}.${S3_ENDPOINT}/${S3_PREFIX}${FILE}" \
+        2>&1 \
+    )
 
-    echo "uploaded ${FILE}"
+    if echo "$R1" | grep "<Error>" > /dev/null 2>&1 ; then
+        echo "FAILED uploading ${FILE}"
+        echo "${R1}"
+
+        EXIT_CODE=1
+    else
+        echo $(date) "uploaded ${FILE}"
 
 
-    echo "removing ${FILE}"
+        echo $(date) "removing ${FILE}"
 
-    rm "${FILE}"
+        rm "${FILE}"
 
-    echo "removed ${FILE}"
+        echo $(date) "removed ${FILE}"
+    fi
 done
 
+exit $EXIT_CODE
